sonar.projectKey=nnmt2810_devops-project-yas
sonar.organization=devops-project-yas
sonar.sources=.
sonar.exclusions=**/*Test.java,**/test/**,**/target/**,**/node_modules/**,.git/**,**/coverage/**
sonar.java.binaries=**/target/classes
sonar.java.libraries=**/target/dependency/*.jar
sonar.coverage.exclusions=**/test/**,**/target/**
sonar.java.source=21
EOF