sonar.projectKey=nnmt2810_devops-project-yas
sonar.organization=nnmt2810
sonar.sources=.
sonar.exclusions=**/*Test.java,**/test/**,**/target/**,**/node_modules/**,.git/**,**/coverage/**
sonar.java.source=11
EOF